defaults:
  - model_registry
  - _self_
data:
  train_path: '.data/train.csv'
  test_path: '.data/test.csv'
  submit_path: '.data'
  submit_name: 'submition.csv'
  ans_path: '.data/solution.csv'
  ratio:
    train: 0.7
    val: 0.3
  lseq: 12
  step: 12
  augment: 2
  target: 'ST'
  used_features: ['baropressure',
                  'humidity',
                  'temperature',
                  'winddirection',
                  'windspeed',
                  'n']
  date: 'Date'
  nfeats: 19
  use_target_in_params: False
  hours:
    hours_in_two_month: 1440
    hours_in_month: 720
    hours_in_week: 168
    hours_in_day: 24
  max_miss: 3
  min_true: 6
  drop:
    # less: {'ST': 20000, 'n': 40}
    less: {'ST': 20000}
  # decompose: [24, 168]



training:
  batch_size: 32
  lr: 1e-4
  lr_factor: 0.999
  clip_val: 1
  weight_decay: 1e-4
  n_epochs: 31
  accelerator: cpu
  full_deterministic_mode: True
  log_every_n_steps: 1
  num_workers: 7

artifacts:
  # experiment_name: 'conv'
  checkpoint:
    dirpath: 'checkpoints'
    # filename: 'last'
    save_top_k: 1
    every_n_epochs: 10
    save_last: True
    file_ext: '.ckpt'
  mlflow_url: 'http://127.0.0.1:8080'
